name: CINETIX
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/film/peakblinders.png
    - assets/film/priest.png
    - assets/film/Gatotkaca.jpg
    - assets/film/Gowok.jpg
    - assets/film/Bangkitnya mayit.jpg
    - assets/film/Pangku.jpg
    - assets/film/Sosok ketiga.jpg
    - assets/film/Syirik.jpg
    - assets/film/The nun.jpg
    - assets/film/The conjuring.jpg
    - assets/film2/Adot.jpg
    - assets/food/popcorn.jpg
    - assets/food/coca.jpg
    - assets/food/air.jpg
    - assets/food/cireng.jpg
    - assets/food/fanta.jpg
    - assets/food/french.jpg
    - assets/food/mix plater.jpg
    - assets/food/pepsi.jpg
    - assets/food/tahu.jpg
    - assets/food/tea.jpg
    - assets/food/tempe.jpg